define([
    'polpware-tinymce-tailor/src/util/Quirks',
    'polpware-tinymce-tailor/src/util/Observable',
    'polpware-tinymce-tailor/src/util/Tools',
    'polpware-tinymce-tailor/src/util/Arr',
    'polpware-tinymce-tailor/src/util/LazyEvaluator',
    'polpware-tinymce-tailor/src/util/Promise',
    'polpware-tinymce-tailor/src/util/EventDispatcher',
    'polpware-tinymce-tailor/src/util/Color',
    'polpware-tinymce-tailor/src/util/Fun',
    'polpware-tinymce-tailor/src/util/LocalStorage',
    'polpware-tinymce-tailor/src/util/Uuid',
    'polpware-tinymce-tailor/src/util/JSONRequest',
    'polpware-tinymce-tailor/src/util/Private',
    'polpware-tinymce-tailor/src/util/JSON',
    'polpware-tinymce-tailor/src/util/XHR',
    'polpware-tinymce-tailor/src/util/JSONP',
    'polpware-tinymce-tailor/src/util/VK',
    'polpware-tinymce-tailor/src/util/I18n',
    'polpware-tinymce-tailor/src/util/Class',
    'polpware-tinymce-tailor/src/util/Delay',
    'polpware-tinymce-tailor/src/util/URI',
    'jquery',
    'meld',
    'when',
    'locache',
    'underscore',
    'constraintjs',
    'data-flow',
    'state-machine',
    'backbone',
    'backbone-paginator'
], function(
    Quirks,
    Observable,
    Tools,
    Arr,
    LazyEvaluator,
    Promise,
    EventDispatcher,
    Color,
    Fun,
    LocalStorage,
    Uuid,
    JSONRequest,
    Private,
    JSON,
    XHR,
    JSONP,
    VK,
    I18n,
    Class,
    Delay,
    URI,
    $,
    meld,
    when,
    locache,
    _,
    cjs,
    flow,
    stateMachine,
    backbone
) {

    'use strict';

    return {
        Quirks: Quirks,
        Observable: Observable,
        Tools: Tools,
        Arr: Arr,
        LazyEvaluator: LazyEvaluator,
        Promise: Promise,
        EventDispatcher: EventDispatcher,
        Color: Color,
        Fun: Fun,
        LocalStorage: LocalStorage,
        Uuid: Uuid,
        JSONRequest: JSONRequest,
        Private: Private,
        JSON: JSON,
        XHR: XHR,
        JSONP: JSONP,
        VK: VK,
        I18n: I18n,
        Class: Class,
        Delay: Delay,
        URI: URI,
        jquery: $,
        meld: meld,
        when: when,
        locache: locache,
        underscore: _,
        constraintjs: cjs,
        dataflow: flow,
        backbone: backbone,
        statemachine: stateMachine
    };
});

