/** Declaration file generated by dts-gen */

export = meld;

declare function meld(target: any, pointcut: any, aspect: any, ...args: any[]): any;

declare namespace meld {
    function add(...args: any[]): any;

    function after(target: any, method: any, adviceFunc: any, ...args: any[]): any;

    function afterReturning(target: any, method: any, adviceFunc: any, ...args: any[]): any;

    function afterThrowing(target: any, method: any, adviceFunc: any, ...args: any[]): any;

    function around(target: any, method: any, adviceFunc: any, ...args: any[]): any;

    function before(target: any, method: any, adviceFunc: any, ...args: any[]): any;

    function joinpoint(): any;

    function on(target: any, method: any, adviceFunc: any, ...args: any[]): any;

}

